pub mod opend;
pub mod protocol;

#[cfg(test)]
mod opend_integration_tests;

// Protobuf types generated from vendored OpenD `.proto` files (proto2).
// We include a single synthetic `mod.rs` generated by `prost-build`.
#[allow(clippy::all)]
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/futu_pb/mod.rs"));
}

pub use opend::{
    OpenDClient, OpenDConfig, OpenDConnectionInfo, OpenDEvent, OpenDOrderRef,
    OpenDPlaceOrderRequest, OpenDTradeAccount, OpenDTradeHeader,
};

use anyhow::Context;
use chrono::{DateTime, Duration, Utc};
use rand::{rngs::StdRng, Rng, SeedableRng};
use std::{
    collections::{BTreeMap, BTreeSet},
    sync::Arc,
};
use thiserror::Error;
use tokio::sync::{mpsc, RwLock};
use tokio_stream::{wrappers::ReceiverStream, Stream};
use trader_shared::{Candle, Quote, Symbol};

#[derive(Debug, Error)]
pub enum ConnectorError {
    #[error("connection failed: {0}")]
    ConnectionFailed(String),

    #[error("timeout: {0}")]
    Timeout(String),

    #[error("protocol error: {0}")]
    Protocol(String),

    #[error("remote error (proto_id={proto_id}, ret_type={ret_type}): {ret_msg}")]
    RemoteError {
        proto_id: u32,
        ret_type: i32,
        ret_msg: String,
    },
}

#[derive(Debug, Clone)]
pub struct MarketSubscription {
    pub symbols: Vec<Symbol>,
}

#[derive(Debug, Clone)]
pub struct MockMarketDataConfig {
    pub interval_ms: u64,
}

impl Default for MockMarketDataConfig {
    fn default() -> Self {
        Self { interval_ms: 1_000 }
    }
}

#[derive(Debug)]
pub struct MockMarketData {
    cfg: MockMarketDataConfig,
    state: Arc<RwLock<MockState>>,
}

#[derive(Debug)]
struct MockState {
    subs: BTreeSet<Symbol>,
    prices: BTreeMap<Symbol, f64>,
    volumes: BTreeMap<Symbol, f64>,
    rng: StdRng,
}

impl MockMarketData {
    pub fn new(cfg: MockMarketDataConfig) -> Self {
        Self {
            cfg,
            state: Arc::new(RwLock::new(MockState {
                subs: BTreeSet::new(),
                prices: BTreeMap::new(),
                volumes: BTreeMap::new(),
                rng: StdRng::seed_from_u64(1337),
            })),
        }
    }

    pub async fn set_subscription(&self, sub: MarketSubscription) {
        let mut s = self.state.write().await;
        s.subs = sub.symbols.into_iter().collect();
        let subs: Vec<Symbol> = s.subs.iter().cloned().collect();
        for sym in subs {
            let p0 = seed_price(&sym);
            s.prices.entry(sym.clone()).or_insert(p0);
            s.volumes.entry(sym).or_insert(0.0);
        }
    }

    pub async fn get_last_quote(&self, symbol: &str) -> Option<Quote> {
        let s = self.state.read().await;
        let last = *s.prices.get(symbol)?;
        let vol = *s.volumes.get(symbol).unwrap_or(&0.0);
        Some(Quote {
            symbol: symbol.to_string(),
            ts: Utc::now(),
            bid: (last * 0.999).max(0.01),
            ask: last * 1.001,
            last,
            volume: vol,
        })
    }

    /// Deterministic synthetic candles.
    pub async fn get_candles(&self, symbol: &str, interval_sec: u32, limit: usize) -> Vec<Candle> {
        let now = Utc::now();
        let mut rng = StdRng::seed_from_u64(hash_symbol(symbol) ^ (interval_sec as u64));
        let mut price = seed_price(symbol);
        let mut out = Vec::with_capacity(limit);
        for i in (0..limit).rev() {
            let ts = now - Duration::seconds((i as i64) * (interval_sec as i64));
            let open = price;
            let drift = (rng.gen::<f64>() - 0.5) * 0.02;
            let close = (open * (1.0 + drift)).max(0.01);
            let high = open.max(close) * (1.0 + rng.gen::<f64>() * 0.005);
            let low = open.min(close) * (1.0 - rng.gen::<f64>() * 0.005);
            let volume = 1000.0 + rng.gen::<f64>() * 500.0;
            out.push(Candle {
                symbol: symbol.to_string(),
                ts,
                interval_sec,
                open,
                high,
                low,
                close,
                volume,
            });
            price = close;
        }
        out
    }

    /// Stream mock quotes for subscribed symbols.
    pub async fn quote_stream(&self) -> impl Stream<Item = Quote> {
        let (tx, rx) = mpsc::channel::<Quote>(1024);
        let state = self.state.clone();
        let interval_ms = self.cfg.interval_ms;

        tokio::spawn(async move {
            let mut ticker = tokio::time::interval(std::time::Duration::from_millis(interval_ms));
            loop {
                ticker.tick().await;
                let mut s = state.write().await;
                let ts = Utc::now();

                for sym in s.subs.clone().into_iter() {
                    // Compute randomness first to avoid overlapping mutable borrows.
                    let shock = (s.rng.gen::<f64>() - 0.5) * 0.01;
                    let vol_add = 10.0 + s.rng.gen::<f64>() * 20.0;

                    let price = {
                        let p = s
                            .prices
                            .entry(sym.clone())
                            .or_insert_with(|| seed_price(&sym));
                        *p = (*p * (1.0 + shock)).max(0.01);
                        *p
                    };
                    let volume = {
                        let vol = s.volumes.entry(sym.clone()).or_insert(0.0);
                        *vol += vol_add;
                        *vol
                    };
                    let q = Quote {
                        symbol: sym.clone(),
                        ts,
                        bid: (price * 0.999).max(0.01),
                        ask: price * 1.001,
                        last: price,
                        volume,
                    };

                    if tx.try_send(q).is_err() {
                        // Backpressure: drop instead of unbounded growth.
                    }
                }
            }
        });

        ReceiverStream::new(rx)
    }
}

fn hash_symbol(symbol: &str) -> u64 {
    // Stable, fast-ish hash (not cryptographic).
    let mut h: u64 = 1469598103934665603;
    for b in symbol.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(1099511628211);
    }
    h
}

fn seed_price(symbol: &str) -> f64 {
    // 10..200 based on symbol hash.
    let h = hash_symbol(symbol);
    10.0 + (h % 190) as f64
}

pub fn parse_opend_addr(host: &str, port: u16) -> anyhow::Result<String> {
    if host.trim().is_empty() {
        anyhow::bail!("host is empty");
    }
    Ok(format!("{host}:{port}"))
}

pub fn parse_rfc3339(ts: &str) -> anyhow::Result<DateTime<Utc>> {
    DateTime::parse_from_rfc3339(ts)
        .context("invalid timestamp")
        .map(|dt| dt.with_timezone(&Utc))
}
